# Generated by Django 3.1.7 on 2021-03-06 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.DateField(max_length=20)),
                ('check_in_times', models.TimeField(blank=True, max_length=20)),
                ('in_location', models.CharField(max_length=80)),
                ('in_ip', models.CharField(max_length=20)),
                ('check_out_time', models.TimeField(blank=True, max_length=20)),
                ('out_location', models.CharField(max_length=80)),
                ('out_ip', models.CharField(max_length=20)),
                ('current_project', models.CharField(blank=True, max_length=30)),
                ('billable_task', models.TextField(blank=True)),
                ('break_time', models.TextField(blank=True, max_length=20)),
                ('task_owner', models.CharField(blank=True, max_length=30)),
                ('approved_by', models.CharField(blank=True, max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
