# Generated by Django 3.1.7 on 2021-03-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelSheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='in_ip',
            field=models.CharField(max_length=30),
        ),
    ]
