# Generated by Django 3.1.7 on 2021-03-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelSheet', '0002_auto_20210306_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='approved_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='billable_task',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='break_time',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='check_in_times',
            field=models.TimeField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='check_out_time',
            field=models.TimeField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='current_project',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='in_ip',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='in_location',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='out_ip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='out_location',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='task_owner',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
