# Generated by Django 3.1.7 on 2021-03-15 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExcelSheet', '0003_auto_20210308_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='approved_by',
            field=models.CharField(default='Pending', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='billable_task',
            field=models.TextField(default='Pending', null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='break_time',
            field=models.TextField(default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='current_project',
            field=models.CharField(default='Pending', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='in_location',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='out_location',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='task_owner',
            field=models.CharField(default='Pending', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_time', models.DateTimeField(max_length=20)),
                ('feedback', models.TextField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
