# Generated by Django 3.1.7 on 2021-03-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelSheet', '0005_auto_20210317_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='media'),
        ),
    ]
