# Generated by Django 3.1.7 on 2021-03-18 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExcelSheet', '0007_auto_20210318_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='trainer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='FeedbackReqest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.CharField(max_length=30, null=True)),
                ('feedback_request', models.BooleanField(default=False)),
                ('request_time', models.DateTimeField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
