# Generated by Django 3.1.7 on 2021-03-18 11:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExcelSheet', '0008_auto_20210318_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackReqest',
            new_name='FeedbackRequest',
        ),
    ]
