# Generated by Django 3.1.7 on 2021-03-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelSheet', '0009_auto_20210318_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='file',
        ),
    ]
